AllCops:
  Include:
    - config.ru
    - 'rakelib/**/*.rake'
    - 'lib/tasks/**/*.rake'
  Exclude:
    - 'bin/**/*'

Style/AlignHash:
  EnforcedHashRocketStyle: table

Style/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Style/TrailingBlankLines:
  EnforcedStyle: final_newline
