## enforce personal preferences

# a  => b
# aa => b
Style/AlignHash:
  EnforcedHashRocketStyle: table

# block {|x| do_something_with x }
Style/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false


## enable all Cops

Style/CollectionMethods:
  Enabled: true

Style/Encoding:
  Enabled: true

Style/InlineComment:
  Enabled: true

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/SymbolArray:
  Enabled: true
